-- MySQL Script generated by MySQL Workbench
-- Sun Sep  7 17:57:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema techtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techtube` DEFAULT CHARACTER SET utf8 ;
USE `techtube` ;

-- -----------------------------------------------------
-- Table `techtube`.`tb_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`tb_cadastro` (
  `idtb_cadastro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo_usuario` ENUM('aluno', 'professor', 'admin') NOT NULL DEFAULT 'aluno',
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idtb_cadastro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `tb_cadastro_idtb_cadastro` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_tb_cadastro1_idx` (`tb_cadastro_idtb_cadastro` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_tb_cadastro1`
    FOREIGN KEY (`tb_cadastro_idtb_cadastro`)
    REFERENCES `techtube`.`tb_cadastro` (`idtb_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(50) NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NOT NULL,
  `carga_horaria` INT NOT NULL,
  `descricao_curso` TEXT NULL,
  `url_perfil_curso` VARCHAR(255) NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_curso_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `techtube`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`his_pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`his_pontuacao` (
  `idhis_pontuacao` INT NOT NULL AUTO_INCREMENT,
  `pontuacao` FLOAT NULL DEFAULT 0,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idhis_pontuacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `tb_cadastro_idtb_cadastro` INT NOT NULL,
  `his_pontuacao_idhis_pontuacao` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idaluno`),
  INDEX `fk_aluno_tb_cadastro1_idx` (`tb_cadastro_idtb_cadastro` ASC) VISIBLE,
  INDEX `fk_aluno_his_pontuacao1_idx` (`his_pontuacao_idhis_pontuacao` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_tb_cadastro1`
    FOREIGN KEY (`tb_cadastro_idtb_cadastro`)
    REFERENCES `techtube`.`tb_cadastro` (`idtb_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_his_pontuacao1`
    FOREIGN KEY (`his_pontuacao_idhis_pontuacao`)
    REFERENCES `techtube`.`his_pontuacao` (`idhis_pontuacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `siape` VARCHAR(10) NOT NULL,
  `tb_cadastro_idtb_cadastro` INT NOT NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  `criado` DATETIME NOT NULL,
  `atualizado` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`idprofessor`),
  INDEX `fk_professor_tb_cadastro1_idx` (`tb_cadastro_idtb_cadastro` ASC) VISIBLE,
  CONSTRAINT `fk_professor_tb_cadastro1`
    FOREIGN KEY (`tb_cadastro_idtb_cadastro`)
    REFERENCES `techtube`.`tb_cadastro` (`idtb_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `curso_idcurso` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_curso_has_tb_cadastro_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  INDEX `fk_turma_professor1_idx` (`professor_idprofessor` ASC) VISIBLE,
  PRIMARY KEY (`idturma`),
  CONSTRAINT `fk_curso_has_tb_cadastro_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `techtube`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `techtube`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`atividade` (
  `idatividade` INT NOT NULL AUTO_INCREMENT,
  `nome_atividade` VARCHAR(100) NOT NULL,
  `conteudo_atividade` TEXT NULL,
  `curso_idcurso` INT NOT NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  PRIMARY KEY (`idatividade`),
  INDEX `fk_atividade_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_atividade_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `techtube`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`url_imagem_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`url_imagem_curso` (
  `idurl_imagem` INT NOT NULL AUTO_INCREMENT,
  `nome_imagem` VARCHAR(50) NULL,
  `url_imagem` VARCHAR(255) NOT NULL,
  `tipo_imagem` VARCHAR(1) NULL,
  `curso_idcurso` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idurl_imagem`),
  INDEX `fk_url_imagem_curso_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_url_imagem_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `techtube`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`url_imagem_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`url_imagem_atividade` (
  `idurl_imagem` INT NOT NULL AUTO_INCREMENT,
  `atividade_idatividade` INT NOT NULL,
  `nome_imagem` VARCHAR(50) NULL,
  `url_imagem` VARCHAR(255) NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idurl_imagem`),
  INDEX `fk_url_imagem_atividade_atividade1_idx` (`atividade_idatividade` ASC) VISIBLE,
  CONSTRAINT `fk_url_imagem_atividade_atividade1`
    FOREIGN KEY (`atividade_idatividade`)
    REFERENCES `techtube`.`atividade` (`idatividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`url_imagem_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`url_imagem_perfil` (
  `idurl_imagem` INT NOT NULL AUTO_INCREMENT,
  `nome_imagem` VARCHAR(50) NULL,
  `url_imagem` VARCHAR(255) NOT NULL,
  `tipo_imagem` VARCHAR(1) NULL,
  `tb_cadastro_idtb_cadastro` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idurl_imagem`),
  INDEX `fk_url_imagem_perfil_tb_cadastro1_idx` (`tb_cadastro_idtb_cadastro` ASC) VISIBLE,
  CONSTRAINT `fk_url_imagem_perfil_tb_cadastro1`
    FOREIGN KEY (`tb_cadastro_idtb_cadastro`)
    REFERENCES `techtube`.`tb_cadastro` (`idtb_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`url_video_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`url_video_curso` (
  `idurl_video` INT NOT NULL AUTO_INCREMENT,
  `nome_video` VARCHAR(50) NULL,
  `url_video` VARCHAR(255) NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idurl_video`),
  INDEX `fk_url_imagem_curso_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_url_imagem_curso_curso10`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `techtube`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtube`.`turma_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtube`.`turma_aluno` (
  `turma_idturma` INT NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  `criado` DATETIME NOT NULL DEFAULT now(),
  `atualizado` DATETIME NULL,
  `excluido` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_turma_has_aluno_aluno1_idx` (`aluno_idaluno` ASC) VISIBLE,
  INDEX `fk_turma_has_aluno_turma1_idx` (`turma_idturma` ASC) VISIBLE,
  PRIMARY KEY (`turma_idturma`, `aluno_idaluno`),
  CONSTRAINT `fk_turma_has_aluno_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `techtube`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_aluno_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `techtube`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
